[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short

[coverage:run]
source = src, creational_patterns
omit = tests/*

[coverage:report]
show_missing = true
skip_covered = false